spring.application.name=demo

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
# Upstash requiere conexión segura (SSL)
spring.data.redis.ssl.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.forward-headers-strategy=framework

server.port=${PORT:8080}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=WHEN_AUTHORIZED

# Actuator
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.metrics.tags.application=finance-tracker-backend
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.health.mail.enabled=false


resilience4j.circuitbreaker.instances.exchangeRate.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.exchangeRate.slidingWindowSize=10
resilience4j.circuitbreaker.instances.exchangeRate.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.exchangeRate.failureRateThreshold=50
resilience4j.circuitbreaker.instances.exchangeRate.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.exchangeRate.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.exchangeRate.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.retry.instances.exchangeRate.maxAttempts=3
resilience4j.retry.instances.exchangeRate.waitDuration=500ms

spring.rabbitmq.addresses=${RABBITMQ_URL:amqp://guest:guest@localhost:5672}
spring.rabbitmq.ssl.enabled=${RABBITMQ_SSL:false}
spring.rabbitmq.listener.simple.missing-queues-fatal=false
# Reintentos del consumer si falla el procesamiento
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.default-requeue-rejected=false

spring.main.lazy-initialization=true
spring.jpa.open-in-view=false
spring.rabbitmq.connection-timeout=3000

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend-url=${FRONTEND_URL:http://localhost:3000}
